### PR TITLE
Enable REMI repos for rhel systems

### PR DESCRIPTION
**Pull request by Sauraus**
Signed-off-by: Antek S. Baranski <antek.baranski@gmail.com>

Step #1 in addressing https://github.com/chef-cookbooks/php/issues/173 and https://github.com/chef-cookbooks/php/issues/190

### CODE REVIEW

**Comment by Sauraus** [comment]
@tas50 what about this PR? :) Feels like it does not add fluff to the cookbook that should not be here, it just allows you to install PHP versions not found in the default repos.

**Comment by iennae** [comment]
Hi, There is a whole cookbook that handles this right now at https://github.com/chef-cookbooks/yum-remi-chef

**Comment by Sauraus** [comment]
Are you suggesting moving the setup of remi php repos to a wrapper cookbook instead of having that in the php cookbook?

**Comment by iennae** [comment]
Based on the comments to #173 this appears to be no longer necessary. Please take a look and verify. Reopen with additional details if it's not sufficient to your needs.

**Pull request closed without merging**
