### PR TITLE
Use an attribute to control whether to manage symlink source

### PR DESCRIPTION
**Pull request by jorhett**
Gets rid of deprecation warnings.

### CODE REVIEW

**Comment by chef-supermarket** [comment]
Hi. I am an automated pull request bot named Curry. There are commits in this pull request whose authors are not yet authorized to contribute to Chef Software, Inc. projects or are using a non-GitHub verified email address. To become authorized to contribute, you will need to sign the Contributor License Agreement (CLA) as an individual or on behalf of your company. [You can read more on Chef's blog.](https://www.chef.io/blog/2014/06/23/changes-to-the-contributor-license-agreement-process)

## Non-GitHub Verified Committers

There are 1 commit author(s) whose commits are authored by a non-GitHub verified email address. Chef will have to manually verify that they are authorized to contribute.

[Please sign the CLA here.](https://supermarket.chef.io/become-a-contributor)

**Comment by jorhett** [comment]
CLA was signed.

**Comment by dodiaraculus17** [comment]
**Sorry about Advertising**

I need contributors for my project. If you would like to help the project is located here.
https://github.com/poKe-Websites/poKe-CMS

Thank You :)

**Comment by iennae** [comment]
Hey @jorhett,

Apologies for the delay in responding to this pull request. Can you rebase your change please so I can pull this in?

Thanks.

**Comment by tas50** [comment]
Closing this out since we never got a response. Feel free to open it up again if it's still an issue

**Pull request closed without merging**
