### PR TITLE
[GH-151] - Adding php-extension Priority Support

### PR DESCRIPTION
**Pull request by amvapor**
- adding the ability to add the ; priority=## comment to php module files
- this allows php5enmod to properly prioritize modules.

### CODE REVIEW

**Comment by chef-supermarket** [comment]
Hi. I am an automated pull request bot named Curry. There are commits in this pull request whose authors are not yet authorized to contribute to Chef Software, Inc. projects or are using a non-GitHub verified email address. To become authorized to contribute, you will need to sign the Contributor License Agreement (CLA) as an individual or on behalf of your company. [You can read more on Chef's blog.](https://www.chef.io/blog/2014/06/23/changes-to-the-contributor-license-agreement-process)

## Non-GitHub Verified Committers

There are 1 commit author(s) whose commits are authored by a non-GitHub verified email address. Chef will have to manually verify that they are authorized to contribute.

[Please sign the CLA here.](https://supermarket.chef.io/become-a-contributor)

**Comment by dodiaraculus17** [comment]
**Sorry about Advertising**

I need contributors for my project. If you would like to help the project is located here.
https://github.com/poKe-Websites/poKe-CMS

Thank You :)

**Comment by tas50** [comment]
@amvapor If you can sign this for the DCO I'd gladly merge it in and release it. https://blog.chef.io/2016/09/19/introducing-developer-certificate-of-origin/

**Comment by amvapor** [comment]
@tas50 I believe I have now done so correctly. Thank you

**Comment by damacus** [comment]
This can be closed in favour of #219. As I've ported the fixes intot that. 

Thanks @amvapor

**Comment by tas50** [comment]
Merged this in #219

**Pull request closed without merging**
