### PR TITLE
[fix] bug fixes related with Ubuntu 16.04 and PHP 7 support

### PR DESCRIPTION
**Pull request by mskurski**
### Description
Changes are related with  #169 "PHP7 / Ubuntu 16.04 & PHP-FPM Pool Listen User/Group" merge request. This merge request caused small bug related with listening php7.0-fpm.sock (which for PHP 7 is configured to /var/run/php/php7.0-fpm.sock) so web server was not working properly (in my case nginx was not listening correct socket for fpm). There are also some small changes added to modules which are just parametrization of php modules, just to have more flexibility and be able to use different modules for differend distributions or PHP versions (I'm aware that this modules are deprecated and will be removed in next versions of cookbook, but for now when they are still in repo it would be nite to have it working).

### CODE REVIEW

**Comment by chef-supermarket** [comment]
Hi. I am an automated pull request bot named Curry. There are commits in this pull request whose authors are not yet authorized to contribute to Chef Software, Inc. projects or are using a non-GitHub verified email address. To become authorized to contribute, you will need to sign the Contributor License Agreement (CLA) as an individual or on behalf of your company. [You can read more on Chef's blog.](https://www.getchef.com/blog/2014/06/23/changes-to-the-contributor-license-agreement-process)

## GitHub Users Who Are Not Authorized To Contribute

The following GitHub users do not appear to have signed a CLA:

* @mskurski

[Please sign the CLA here.](https://supermarket.chef.io/become-a-contributor)

**Comment by aight8** [comment]
Please merge

**Comment by iennae** [comment]
@mskurski can you please sign the CLA? Also for +attribute :listen, default: node['php']['fpm_socket'], can you add a kind of validator? Thanks!

**Comment by iennae** [comment]
@mskurski I'd love to merge this. Could you please sign the CLA or confirm that you have signed in the past? Thanks!

**Comment by chef-supermarket** [comment]
Hi. Your friendly Curry bot here. Just letting you know that all commit authors have become authorized to contribute. I have added the "Signed CLA" label to this issue so it can easily be found in the future.

**Comment by mskurski** [comment]
Hi @iennae,

my apologise for the delay but I'm quite busy now so I will be able to add the validator for "fpm_socket" parameter on Wednesday or even Thursday so sorry for that inconvenience.

Best regards,
Marcin

**Comment by iennae** [comment]
@mskurski Thanks so much! Appreciate the fix!

**Pull request merged**
